# Generated by Django 2.1.7 on 2019-03-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayakapi', '0002_auto_20190327_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['cost']},
        ),
    ]
